### ISSUE TITLE
Add bottom margin to <ul>

### ISSUE THREAD

**Issue by bartekn** [stellar/developers#36]
![](https://cloud.githubusercontent.com/assets/464938/12267859/73cf4578-b94a-11e5-8be1-9802748d2c02.png)

**Comment by irisli** [comment]
I've looked in to the issue. I've checked most other places that use lists and none of them need additional margin bottom. The reason is that most list items have a `<p>` inside which has a default 1em bottom margin. The example you screenshotted has no bottom spacing because there was a lack of newlines in between the list item.

**Comment by irisli** [comment]
Here is a demonstration using the actual css and parser of the developer site:
![image](https://cloud.githubusercontent.com/assets/5728307/12367586/fd5a4ef6-bb97-11e5-8334-da22e2a64a45.png)

**Comment by bartekn** [comment]
This seems odd because lists with no newlines are correct markdown syntax.

**Comment by irisli** [comment]
Okay thats a good point. I've thought about it again and decided to add bottom margin to `ul` and `ol`. When a `li` has a `p` tag with margin, that margin will collapse with the `ul/ol` margin meaning no duplication of margin.
